### ISSUE TITLE
Ref - Design

### ISSUE THREAD

**Issue by rustywoman** [rustywoman/paparazzi#20]
- Fix Design
- Responsive

**Comment by rustywoman** [comment]
### Item List

- URL
- タイトル
- 全画面スクリーンショット
- メタ（metaタグ抜粋）
- 生テキスト
- CSS
  - 全スタイルのステータス
    - セレクタ総数
    - OK（使用されているセレクタ）数
    - NG（定義のみで、使用されていないセレクタ）数
    - Unknown（擬似要素、DOM取得不可なセレクタ）数
  - インラインスタイルのステータス
    - セレクタ総数
    - OK数
    - NG数
    - Unknown数
    - 各セレクタの実態
      - セレクタ定義
      - 出現DOM数
  - 外部スタイルのステータス
    - 外部ファイル名
    - セレクタ総数
    - OK数
    - NG数
    - Unknown数
    - 各セレクタの実態
      - セレクタ定義
      - 出現DOM数
- JavaScript
  - インラインスクリプトのステータス（定義の抜粋）
  - 外部スクリプトのステータス
    - 外部ファイル名
    - _blankリンク
- Image
  - Full Path
  - 200 / 40X の 読込ステータス
  - 実際の画像（localhostを参照）

---

### ToDo

- [ ] ワイヤーの引き直し
- [ ] Templateの修正

---

### Q

- [ ] スクリーンショット領域が大きすぎる（コンテンツ領域に幅100%だと大きすぎる）
- [ ] highlight.jsが浮いている（metaとinline scriptのみに利用）
- [ ] 生テキストをテーブル表現すべきか否か（wordmapとか、要見せ方を検討）
- [ ] CSSの調査結果が大きすぎる（サイズ感調整）
- [ ] localhostへの非同期通信コスト（最小同時取得数を再検討）
